FROM maven:3.9.14-eclipse-temurin-21 AS api-builder

WORKDIR /opt/veriguard-build/veriguard
COPY veriguard-model ./veriguard-model
COPY veriguard-framework ./veriguard-framework
COPY veriguard-api ./veriguard-api
COPY veriguard-front/builder/prod/build ./veriguard-front/builder/prod/build
COPY pom.xml ./pom.xml
RUN mvn install -DskipTests -Pdev

FROM eclipse-temurin:21.0.10_7-jre AS app

RUN ln -s /usr/bin/dpkg-split /usr/sbin/dpkg-split
RUN ln -s /usr/bin/dpkg-deb /usr/sbin/dpkg-deb
RUN ln -s /bin/rm /usr/sbin/rm
RUN ln -s /bin/tar /usr/sbin/tar
RUN DEBIAN_FRONTEND=noninteractive apt-get update -q && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y tini && rm -rf /var/lib/apt/lists/*
COPY --from=api-builder /opt/veriguard-build/veriguard/veriguard-api/target/veriguard-api.jar ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["java", "-jar", "veriguard-api.jar"]
