package io.veriguard.database.raw;

import java.util.List;
import java.util.Set;

/**
 * Spring Data projection interface for attackChainNode data with relationships.
 *
 * <p>This interface defines a projection for retrieving attackChainNode information including
 * associated teams, assets, expectations, and execution metadata. Used for efficient bulk
 * operations and queries that require attackChainNode relationship data without full entity
 * loading.
 *
 * @see io.veriguard.database.model.AttackChainNode
 */
public interface RawAttackChainNode {

  /**
   * Returns the unique identifier of the attackChainNode.
   *
   * @return the attackChainNode ID
   */
  String getNode_id();

  /**
   * Returns the ID of the associated asset group.
   *
   * @return the asset group ID, or {@code null} if not associated with an asset group
   */
  String getAsset_group_id();

  /**
   * Returns the list of team IDs targeted by this attackChainNode.
   *
   * @return list of team IDs
   */
  List<String> getNode_teams();

  /**
   * Returns the list of individual asset IDs targeted by this attackChainNode.
   *
   * @return list of asset IDs
   */
  List<String> getNode_assets();

  /**
   * Returns the list of asset group IDs targeted by this attackChainNode.
   *
   * @return list of asset group IDs
   */
  List<String> getNode_asset_groups();

  /**
   * Returns the list of expectation IDs defined for this attackChainNode.
   *
   * @return list of expectation IDs
   */
  List<String> getNode_expectations();

  /**
   * Returns the set of communication IDs generated by this attackChainNode.
   *
   * @return set of communication IDs
   */
  Set<String> getNode_communications();

  /**
   * Returns the set of platforms this attackChainNode targets.
   *
   * @return set of platform types (e.g., "Linux", "Windows", "macOS")
   */
  Set<String> getNode_platforms();

  /**
   * Returns the set of kill chain phase IDs associated with this attackChainNode.
   *
   * @return set of kill chain phase IDs
   */
  Set<String> getNode_kill_chain_phases();

  /**
   * Returns the current execution status name of the attackChainNode.
   *
   * @return the status name (e.g., "PENDING", "EXECUTING", "SUCCESS", "ERROR")
   */
  String getStatus_name();

  /**
   * Returns the ID of the attackChain this attackChainNode belongs to.
   *
   * @return the attackChain ID, or {@code null} if part of an attackChainRun only
   */
  String getNode_attackChain();
}
