package io.veriguard.database.raw;

import java.util.List;
import java.util.Set;

/**
 * Spring Data projection interface for inject data with relationships.
 *
 * <p>This interface defines a projection for retrieving inject information including associated
 * teams, assets, expectations, and execution metadata. Used for efficient bulk operations and
 * queries that require inject relationship data without full entity loading.
 *
 * @see io.veriguard.database.model.Inject
 */
public interface RawInject {

  /**
   * Returns the unique identifier of the inject.
   *
   * @return the inject ID
   */
  String getInject_id();

  /**
   * Returns the ID of the associated asset group.
   *
   * @return the asset group ID, or {@code null} if not associated with an asset group
   */
  String getAsset_group_id();

  /**
   * Returns the list of team IDs targeted by this inject.
   *
   * @return list of team IDs
   */
  List<String> getInject_teams();

  /**
   * Returns the list of individual asset IDs targeted by this inject.
   *
   * @return list of asset IDs
   */
  List<String> getInject_assets();

  /**
   * Returns the list of asset group IDs targeted by this inject.
   *
   * @return list of asset group IDs
   */
  List<String> getInject_asset_groups();

  /**
   * Returns the list of expectation IDs defined for this inject.
   *
   * @return list of expectation IDs
   */
  List<String> getInject_expectations();

  /**
   * Returns the set of communication IDs generated by this inject.
   *
   * @return set of communication IDs
   */
  Set<String> getInject_communications();

  /**
   * Returns the set of platforms this inject targets.
   *
   * @return set of platform types (e.g., "Linux", "Windows", "macOS")
   */
  Set<String> getInject_platforms();

  /**
   * Returns the set of kill chain phase IDs associated with this inject.
   *
   * @return set of kill chain phase IDs
   */
  Set<String> getInject_kill_chain_phases();

  /**
   * Returns the current execution status name of the inject.
   *
   * @return the status name (e.g., "PENDING", "EXECUTING", "SUCCESS", "ERROR")
   */
  String getStatus_name();

  /**
   * Returns the ID of the scenario this inject belongs to.
   *
   * @return the scenario ID, or {@code null} if part of an exercise only
   */
  String getInject_scenario();
}
