package io.veriguard.rest.agent;

import io.swagger.v3.oas.annotations.Operation;
import io.veriguard.aop.RBAC;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import java.io.IOException;
import java.io.InputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Locale;
import java.util.Optional;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

/**
 * Veriguard Agent (C1) — install script + binary endpoints (Tailscale 风格 one-line curl).
 *
 * <p>Endpoints:
 *
 * <ul>
 *   <li>{@code GET /api/agent/install/{token}} — render bash one-liner with embedded onboard_token;
 *       auto-detects {@code os/arch} via {@code uname -m / uname -s}; downloads binary; runs {@code
 *       veriguard-agent init --bootstrap}
 *   <li>{@code GET /api/agent/install/{token}/ps1} — PowerShell equivalent for Windows
 *   <li>{@code GET /api/agent/install/binary/{os}/{arch}} — stream binary from {@code
 *       classpath:agents/veriguard-agent/<os>/<arch>/veriguard-agent[.exe]}, with X-SHA256 header
 *       for client-side integrity check
 * </ul>
 *
 * <p>Token semantics: bootstrap tokens consumed by these endpoints are the same onboard_token
 * generated by {@link AgentOnboardingService#init}. Single-use enforcement is deferred to
 * C1-Platform-3 (current behavior allows repeat fetches while the token has not been used by {@code
 * /onboard/register}).
 *
 * <p>If the binary classpath resource is missing (e.g. a fresh checkout where the CI release
 * pipeline has not yet dropped real binaries), the endpoint returns 404 with a clear message —
 * deliberately fail visibly so operators do not run a placeholder.
 */
@RestController
public class AgentInstallScriptApi {

  public static final String INSTALL_BASH_URI = "/api/agent/install/{token}";
  public static final String INSTALL_PS1_URI = "/api/agent/install/{token}/ps1";
  public static final String INSTALL_BINARY_URI = "/api/agent/install/binary/{os}/{arch}";

  /** Allowed OS values for binary download path. */
  static final String OS_PATTERN = "linux|macos|windows";

  /** Allowed arch values for binary download path. */
  static final String ARCH_PATTERN = "x86_64|arm64";

  private static final String CLASSPATH_BASE = "classpath:agents/veriguard-agent/";

  private final AgentOnboardingService onboardingService;
  private final PlatformIdentityService platformIdentity;
  private final PathMatchingResourcePatternResolver resourceResolver =
      new PathMatchingResourcePatternResolver();

  public AgentInstallScriptApi(
      AgentOnboardingService onboardingService, PlatformIdentityService platformIdentity) {
    this.onboardingService = onboardingService;
    this.platformIdentity = platformIdentity;
  }

  @GetMapping(value = INSTALL_BASH_URI, produces = "text/x-shellscript;charset=UTF-8")
  @Operation(summary = "Render bash one-liner install script (Unix install_pack bootstrap)")
  @RBAC(skipRBAC = true)
  public ResponseEntity<String> bashInstall(@PathVariable("token") @NotBlank String token) {
    Optional<AgentOnboardingService.AgentOnboardingState> state =
        onboardingService.findByToken(token);
    if (state.isEmpty()) {
      return ResponseEntity.status(404).build();
    }
    String script = renderBashScript(token, platformIdentity.getPlatformUrl());
    return ResponseEntity.ok().body(script);
  }

  @GetMapping(value = INSTALL_PS1_URI, produces = "text/plain;charset=UTF-8")
  @Operation(
      summary = "Render PowerShell one-liner install script (Windows install_pack bootstrap)")
  @RBAC(skipRBAC = true)
  public ResponseEntity<String> ps1Install(@PathVariable("token") @NotBlank String token) {
    Optional<AgentOnboardingService.AgentOnboardingState> state =
        onboardingService.findByToken(token);
    if (state.isEmpty()) {
      return ResponseEntity.status(404).build();
    }
    String script = renderPowerShellScript(token, platformIdentity.getPlatformUrl());
    return ResponseEntity.ok().body(script);
  }

  @GetMapping(value = INSTALL_BINARY_URI)
  @Operation(summary = "Download veriguard-agent binary (used by install script)")
  @RBAC(skipRBAC = true)
  public ResponseEntity<?> downloadBinary(
      @PathVariable("os") @NotBlank @Pattern(regexp = OS_PATTERN) String os,
      @PathVariable("arch") @NotBlank @Pattern(regexp = ARCH_PATTERN) String arch) {
    String osLower = os.toLowerCase(Locale.ROOT);
    String archLower = arch.toLowerCase(Locale.ROOT);

    String filename = "windows".equals(osLower) ? "veriguard-agent.exe" : "veriguard-agent";
    String resourcePath = CLASSPATH_BASE + osLower + "/" + archLower + "/" + filename;
    Resource binary = resourceResolver.getResource(resourcePath);

    if (!binary.exists() || !binary.isReadable()) {
      return ResponseEntity.status(404)
          .body(
              "agent binary not yet bundled; expected at agents/veriguard-agent/"
                  + osLower
                  + "/"
                  + archLower
                  + "/"
                  + filename);
    }

    byte[] content;
    try (InputStream in = binary.getInputStream()) {
      content = in.readAllBytes();
    } catch (IOException ex) {
      return ResponseEntity.status(500).body("Failed to read agent binary: " + ex.getMessage());
    }

    if (content.length == 0) {
      return ResponseEntity.status(404)
          .body(
              "agent binary placeholder is empty; expected at agents/veriguard-agent/"
                  + osLower
                  + "/"
                  + archLower
                  + "/"
                  + filename);
    }

    String sha256Hex = sha256Hex(content);

    return ResponseEntity.ok()
        .contentType(MediaType.APPLICATION_OCTET_STREAM)
        .header("X-SHA256", sha256Hex)
        .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
        .header(HttpHeaders.CONTENT_LENGTH, String.valueOf(content.length))
        .body(content);
  }

  /**
   * Render the bash one-liner script. Embeds {@code token} + {@code platformUrl} directly. Bash
   * detects {@code os/arch} via {@code uname -s / uname -m}, fetches the binary, verifies SHA-256
   * against the {@code X-SHA256} header, and invokes {@code veriguard-agent init --bootstrap}.
   *
   * <p>Tailscale 风格 — operator only needs to run a single {@code curl <url> | bash} command. Tokens
   * are short-lived (24h TTL — see {@link AgentOnboardingService#ONBOARD_TOKEN_TTL}); the generated
   * script SHOULD be reviewed with {@code curl ... | less} before piping into bash (per S-2
   * second-layer defense).
   */
  static String renderBashScript(String token, String platformUrl) {
    return ""
        + "#!/usr/bin/env bash\n"
        + "# Veriguard Agent (C1) one-line install — Tailscale style.\n"
        + "# Generated for onboard_token: short-lived (24h TTL).\n"
        + "set -euo pipefail\n"
        + "ONBOARD_TOKEN=\""
        + token
        + "\"\n"
        + "PLATFORM_URL=\""
        + platformUrl
        + "\"\n"
        + "UNAME_S=\"$(uname -s)\"\n"
        + "case \"$UNAME_S\" in\n"
        + "  Linux*)  OS=linux ;;\n"
        + "  Darwin*) OS=macos ;;\n"
        + "  *) echo \"Unsupported OS: $UNAME_S\" >&2; exit 1 ;;\n"
        + "esac\n"
        + "UNAME_M=\"$(uname -m)\"\n"
        + "case \"$UNAME_M\" in\n"
        + "  x86_64|amd64) ARCH=x86_64 ;;\n"
        + "  aarch64|arm64) ARCH=arm64 ;;\n"
        + "  *) echo \"Unsupported arch: $UNAME_M\" >&2; exit 1 ;;\n"
        + "esac\n"
        + "INSTALL_DIR=\"${VERIGUARD_INSTALL_DIR:-/usr/local/bin}\"\n"
        + "TMP_DIR=\"$(mktemp -d)\"\n"
        + "trap 'rm -rf \"$TMP_DIR\"' EXIT\n"
        + "BIN_URL=\"$PLATFORM_URL/api/agent/install/binary/$OS/$ARCH\"\n"
        + "echo \"Downloading veriguard-agent from $BIN_URL\"\n"
        + "HEADERS_FILE=\"$TMP_DIR/headers.txt\"\n"
        + "curl --fail --show-error --silent --location \\\n"
        + "  --dump-header \"$HEADERS_FILE\" \\\n"
        + "  --output \"$TMP_DIR/veriguard-agent\" \\\n"
        + "  \"$BIN_URL\"\n"
        + "EXPECTED_SHA=\"$(awk -F': ' 'tolower($1)==\"x-sha256\" {gsub(/\\r/,\"\",$2); print $2}'"
        + " \"$HEADERS_FILE\")\"\n"
        + "ACTUAL_SHA=\"$(shasum -a 256 \"$TMP_DIR/veriguard-agent\" | awk '{print $1}')\"\n"
        + "if [ -z \"$EXPECTED_SHA\" ] || [ \"$EXPECTED_SHA\" != \"$ACTUAL_SHA\" ]; then\n"
        + "  echo \"SHA-256 mismatch — expected=$EXPECTED_SHA actual=$ACTUAL_SHA\" >&2; exit 1\n"
        + "fi\n"
        + "chmod 0755 \"$TMP_DIR/veriguard-agent\"\n"
        + "if [ -w \"$INSTALL_DIR\" ]; then SUDO=\"\"; else SUDO=\"sudo\"; fi\n"
        + "$SUDO install -m 0755 \"$TMP_DIR/veriguard-agent\" \"$INSTALL_DIR/veriguard-agent\"\n"
        + "echo \"Installed: $INSTALL_DIR/veriguard-agent\"\n"
        + "\"$INSTALL_DIR/veriguard-agent\" init --bootstrap \\\n"
        + "  --onboard-token \"$ONBOARD_TOKEN\" \\\n"
        + "  --platform-url \"$PLATFORM_URL\"\n";
  }

  /**
   * Render the Windows PowerShell one-liner script. Equivalent to {@link #renderBashScript} but for
   * PowerShell on Windows (.exe binary). Detects arch via {@code $env:PROCESSOR_ARCHITECTURE}.
   */
  static String renderPowerShellScript(String token, String platformUrl) {
    return ""
        + "# Veriguard Agent (C1) one-line install (PowerShell) — Tailscale style.\n"
        + "# Generated for onboard_token: short-lived (24h TTL).\n"
        + "$ErrorActionPreference = 'Stop'\n"
        + "$OnboardToken = '"
        + token
        + "'\n"
        + "$PlatformUrl = '"
        + platformUrl
        + "'\n"
        + "switch ($env:PROCESSOR_ARCHITECTURE) {\n"
        + "  'AMD64' { $Arch = 'x86_64' }\n"
        + "  'ARM64' { $Arch = 'arm64' }\n"
        + "  default { Write-Error \"Unsupported arch: $env:PROCESSOR_ARCHITECTURE\"; exit 1 }\n"
        + "}\n"
        + "$BinUrl = \"$PlatformUrl/api/agent/install/binary/windows/$Arch\"\n"
        + "$InstallDir = if ($env:VERIGUARD_INSTALL_DIR) { $env:VERIGUARD_INSTALL_DIR } else"
        + " { 'C:\\Program Files\\Veriguard' }\n"
        + "if (-not (Test-Path $InstallDir)) { New-Item -ItemType Directory -Path $InstallDir |"
        + " Out-Null }\n"
        + "$TmpFile = Join-Path ([IO.Path]::GetTempPath()) ([IO.Path]::GetRandomFileName() +"
        + " '.exe')\n"
        + "Write-Host \"Downloading veriguard-agent from $BinUrl\"\n"
        + "$Resp = Invoke-WebRequest -Uri $BinUrl -OutFile $TmpFile -PassThru\n"
        + "$ExpectedSha = $Resp.Headers['X-SHA256']\n"
        + "$ActualSha = (Get-FileHash -Algorithm SHA256 -Path $TmpFile).Hash.ToLower()\n"
        + "if (-not $ExpectedSha -or $ExpectedSha.ToLower() -ne $ActualSha) {\n"
        + "  Write-Error \"SHA-256 mismatch — expected=$ExpectedSha actual=$ActualSha\";"
        + " exit 1\n"
        + "}\n"
        + "$Target = Join-Path $InstallDir 'veriguard-agent.exe'\n"
        + "Move-Item -Force $TmpFile $Target\n"
        + "Write-Host \"Installed: $Target\"\n"
        + "& $Target init --bootstrap --onboard-token $OnboardToken --platform-url $PlatformUrl\n";
  }

  private static String sha256Hex(byte[] bytes) {
    try {
      MessageDigest md = MessageDigest.getInstance("SHA-256");
      return HexFormat.of().formatHex(md.digest(bytes));
    } catch (NoSuchAlgorithmException ex) {
      throw new IllegalStateException("SHA-256 not available", ex);
    }
  }
}
