name: "[Veriguard] Auto Label"
on:
  pull_request_target:
    branches: [master, release/current]
    types: [opened, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto Label"
        uses: FiligranHQ/filigran-ci-tools/actions/auto-label@main
